---
- name: Fetch Docker Image And Run
  hosts: ubuntu18
  remote_user: server

  tasks:
    - name: pull image
      docker_container:
        name: java_calculator_app
        image: Ajith1402/calculator_app
        pull: yes
        state: started

